Hw-4
Belocherkovec/Lalasia-E-commerce pull request #3
Opened 2024-05-02 08:24 UTC by Belocherkovec

Homework-4

2024-05-06 06:18 UTC, foxtrotkilomike requested changes

2024-05-06 06:18 UTC, foxtrotkilomike commented on src/config/Api.ts
> +    return this.getRequest('api/v1/categories', urlParams, queryParams);
`'api/v1/'` надо было также оставить в `URLS.Platzi`

2024-05-06 06:18 UTC, foxtrotkilomike commented on src/entities/product/types.ts
> +export interface ICategory {
Лучше вынести это в отдельную сущность категории entities/category

2024-05-06 06:18 UTC, foxtrotkilomike commented on readme.md
> +  8. Попытался добавить пагинацию в query параметр, перестала работать пагинация. Описал проблему в комментариях на странице products.
1. По конфигу роутинга всё ок. Но нужно было ещё вынести сами роуты в конфиг, который использовать для ссылок на страницы в коде (когда прописываем пропс to в Link). Писал об этом в прошлом PR, но не написал как конкретно это сделать. В общем, структура такого конфига выглядит следующим образом:

```
const routerUrls = {
	main: '/',
	products: {
		mask: '/products',
		create: () => '/products'
	},
	product: {
		mask: '/product/:id',
		create: (id: number) => `/product/${id}`
	}
}
```

то есть у роута есть поле mask, которое нужно иногда для ручной проверки текущего роута, но в основном используем поле create как раз для создания ссылки на страницу. К примеру ссылка на страницу продукта выглядит так:

```
import { Link } from 'react-router-dom';

const productId = 10;

<Link to={routerUrls.product.create(productId)} />
```

У тебя сейчас роуты захардкожены (=> копипаста во многих частях проекта), из-за чего возник баг — ссылка на страницу продукта в карточке продукта похожих товаров неверная. Из-за этого при клике на нее происходит переход в каталог, а не на страницу продукта.

```
<Link to={`/products/${e.id}`} />
```

2. Да, обычно в App подключают глобальные стили типа сброса, всё верно. Единственное, ты в createRoot().render() передаешь RouterConfig, а это не очень. Мало ли сколько ещё провайдеров будет в приложении, они все должны находиться в одном месте. Обычно делают так — создают отдельный компонент Root, в котором находятся одни провайдеры (это не создаст дополнительные обертки и вложенность в DOM), и его центральным компонентом является RouterProvider. В createRoot().render() передают уже Root. Пример с одного из наших проектов:

```
const Root = () => {
    <WebSocketProvider value={websocketModel.current}>
      <ThemeProvider theme={theme}>
        <RootStoreProvider store={store}>
          <IntlProvider locale="ru" messages={messages}>
            <GlobalModalContextProvider>
              <RouterProvider router={router} />
            </GlobalModalContextProvider>
          </IntlProvider>
        </RootStoreProvider>
      </ThemeProvider>
    </WebSocketProvider>
}
```

3. Да, API ограниченный в этом плане, тут придётся немного костыльно сделать, но тем не менее с соблюдением главного принципа — вся работа со списками (поиск, фильтрация, пагинация) должна происходить через сервер, а не на фронте. Поэтому реализуем пункт 3.3

> 3.3 Делать два запроса, из первого узнать только общее количество запросов, второй будет подгружать новые товары (в таком случае не выйдем за границы).

4. <-- Посмотрю позже во время ревью, когда будет готов код -->

5. <-- Посмотрю позже во время ревью, когда будет готов код -->

6. Не увидел `PaginationProps<any>`

7. Не совсем понял, о каком скачке речь, но сейчас пагинация происходит на фронте и это нужно исправить. Парамеры пагинации нужно сохранять в query строку (и уметь их оттуда доставать при первоначальной загрузке страницы, иначе какой в них толк?). С этими параметрами надо ходить на бэк и каждый раз запрашивать новый кусок списка. При переключении страницы должен происходить скролл в начало страницы (сейчас нет) с `scroll-behavior: smooth`, а также внутри списка вместо элементов должен появляться лоадер во время выполнения запроса.

2024-05-06 06:18 UTC, foxtrotkilomike commented on src/components/Pagination/Pagination.tsx
> +  }
Понял идею про делегирование события клика, но оно тут не нужно, выглядит криво и поддерживать будет тяжело. Типа никто никогда не пишет логику, опираясь на класснеймы. Наоборот — класснеймы должны зависеть от данных, мы не должны данные выковыривать из DOM.

Нужно сделать проще — создать `PaginationModel`, в ней определить три метода — `incrementPage`, `decrementPage`, `goToPage`, и напрямую присвоить эти обработчики кнопкам (правой стрелке, левой стрелке и кнопке с цифрой).

2024-05-06 06:18 UTC, foxtrotkilomike commented on src/components/Pagination/Pagination.tsx
> +}
Эту логику определения массива элементов между стрелками также предлагаю вынести в PaginationModel. Можно сделать геттером, т.к. эти данные зависят от текущей страницы и общего числа элементов. Таким образом, при изменении страницы или общего числа элементов он будет автоматически пересчитываться. count предлагаю переименовать в total, потому что я не сразу въехал, что за абстрактный count.

В этом геттере предлагаю создавать следующую структуру данных — массив конфигов текущей странички (элемента между стрелками). В таком мини-конфиге будет содержаться нужная для рендера информация:

```
type PaginationElement = {
  content: string | number;
  isActive: boolean;
  isDisabled: boolean; // (для троеточия)
}
```

соответственно геттер будет возвращать такой массив `PaginationElement[]`

Далее уже в компоненте рендерим на основе данной структуры данных:

```
{paginationElements.map((e) => (
  <button
    className={cn(
      styles.pagination__item,
      e.isActive && styles.pagination__item_active,
      e.isDisabled && styles.pagination__item_disabled,
    )}
  >
    {e.content}
  </button>
))}
```

поздравляю, вы великолепны — отделили логику данных от отображения!

PS. интерактивные элементы (кликабельные) нужно для доступности делать именно кнопками, а не дивами.

2024-05-06 17:43 UTC, Belocherkovec commented on src/config/Api.ts
> +    return this.getRequest('api/v1/categories', urlParams, queryParams);
done

2024-05-06 17:47 UTC, Belocherkovec commented on src/entities/product/types.ts
> +export interface ICategory {
done

2024-05-08 12:02 UTC, Belocherkovec commented on src/components/Pagination/Pagination.tsx
> +  }
done

2024-05-08 12:02 UTC, Belocherkovec commented on src/components/Pagination/Pagination.tsx
> +}
done

2024-05-09 14:48 UTC, foxtrotkilomike commented on src/components/MultiDropDown/MultiDropDown.tsx
> +      ref.current?.focus();
Тут нужно ещё автоматически закрывать его при выборе опции

2024-05-09 14:48 UTC, foxtrotkilomike commented on src/components/MultiDropDown/MultiDropDown.tsx
> +  };
Вот эта вещь на практике часто используется вместе, поэтому предлагаю сделать отдельный хук useToggleState. В нем будет useState с состоянием isOpen, и несколько useCallback-ов, которые будут это состояние изменять — open, close, toggle. Наружу соответственно хук отдает эти 4 параметра, только не в массиве, а в объекте, чтобы можно было удобно потом доставать только нужные в конкретном компоненте.

2024-05-09 14:48 UTC, foxtrotkilomike commented on src/components/MultiDropDown/MultiDropDown.tsx
> +    const hadlerClick = (e: MouseEvent) => {
hadlerClick опечатка
очень советую поставить расширение Code Spell Checker. А вообще залетай почитать мою статью о полезных плагинах для VS Code (если ты на нем) https://habr.com/ru/companies/kts/articles/779670/

2024-05-09 14:48 UTC, foxtrotkilomike commented on src/components/MultiDropDown/MultiDropDown.tsx
> +export default MultiDropdown;
Как общий совет — тут нетривиальный компонент и у него много колбэков, мемо и всякой логики. Обычно вьюшку (компонент) стараются не перегружать и всю работу с данными выносить в модель, которая назвается также как компонент. В этой модели идет вся работа с данными и ничего не надо мемоизировать. Логика и отображение разделены.

2024-05-09 14:48 UTC, foxtrotkilomike commented on src/config/RouteList.tsx
>      <>
Тут надо заменить строки на использование конфига routerUrls, иначе одно и то же задается в разных местах

2024-05-09 14:48 UTC, foxtrotkilomike commented on src/pages/Categories/Categories.tsx
> +  }, []);
В будущем также надо вынести в стор. В нем — метод по загрузке категорий, поле со списком категорий (не просто массив, а модель списка), состояние загрузки, чтобы отображать лоадер во время запроса.

2024-05-09 14:48 UTC, foxtrotkilomike commented on src/pages/Products/Products.tsx
> +          <Link to={`/products/${e.id}`} key={e.id} className={styles.products__card}>
Нужно везде в проекте заиспользовать routerUrls

2024-05-09 14:48 UTC, foxtrotkilomike commented on src/pages/Products/Products.tsx
> +export default observer(Products);
Не хватает лоадера во время загрузки данных

2024-05-09 14:48 UTC, foxtrotkilomike commented on src/pages/Products/Products.tsx
> +      searchParams.set('search', searchStr);
Эти все состояния и функции должны находиться в ProductStore, он для того и нужен. Здесь можно оставить только один useEffect, который будет вызывать метод стора, ответственный за загрузку первой пачки данных.

Ты же в курсе, что у тебя все эти функции создаются заново на каждый рендер?...

2024-05-09 14:48 UTC, foxtrotkilomike commented on src/store/ProductStore/ProductStore.ts
> +  private _total: number = 1;
PaginationStore также можно сделать полем этого стора, чтобы сразу синхронизировать состояние пагинации, и не считать ничего внутри компонента. PaginationStore можно не делать локальным стором внутри компонента пагинации, а прокидывать саму модель пропсом в него.

2024-05-09 14:48 UTC, foxtrotkilomike commented on src/store/ProductStore/ProductStore.ts
> +      const res = await Api.getProducts([], queryParams);
Нужно добавить состояние загрузки, чтобы показывать лоадер в то время, пока данные грузятся

2024-05-09 14:48 UTC, foxtrotkilomike commented on src/store/ProductStore/ProductStore.ts
> +      console.log(res.data, res.data.length);
Не забывай чистить консоль логи перед пушем. Поможет правило eslint-a `no-console`

2024-05-09 14:57 UTC, foxtrotkilomike commented
Не хватает стора страницы продукта. В нем — метод загрузки продукта, похожих товаров (и поле с состоянием загрузки для показа лоадера или ошибки). В будущем опционально можно добавить состояние добаления в корзину, в избранное.

2024-05-14 16:34 UTC, merged